resource "null_resource" "wait" {
  provisioner "local-exec" {
    command = "sleep 30"
  }

  depends_on = [
    yandex_compute_instance.node01-public
  ]
}

resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
    all:
      vars:
        ansible_connection: ssh
        ansible_user: ubuntu
    nodes:
      hosts:
        node01.netology.yc: 
          ansible_host: ${yandex_compute_instance.node01-public.network_interface.0.nat_ip_address}
     
    DOC
    
  filename = "../inventory/hosts.yml"
    depends_on = [
    null_resource.wait
  ]
}