---
- name: Install Python
  hosts: all
  gather_facts: false
  pre_tasks:
  - name: install python
    become: true
    raw: 'apt update && apt install -y python'
- name: Install
  hosts: nodes
  tasks:
    - name: copy ssh
      copy:
        src: /home/den/.ssh/id_rsa
        dest: /home/ubuntu/.ssh/id_rsa
        owner: ubuntu
        group: ubuntu
        mode: '0600'